version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      - JPDA_ADDRESS=*:8001
      - JPDA_TRANSPORT=dt_socket
    ports:
      - "8080:8080"
      - "8001:8001"
    depends_on:
      - db
  db:
    build:
      context: db
    environment:
      - MYSQL_ROOT_PASSWORD=dsw
      - MYSQL_DATABASE=dsw
      - MYSQL_USER=dsw
      - MYSQL_PASSWORD=dsw
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "9000:8080"
    depends_on:
      - db

volumes:
  dbdata:
